import argparse
import sys
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown

from core.graph import build_graph
from core.state import AgentState
from core.config import get_review_config

console = Console()

def print_banner():
    console.print("[bold cyan]=================================================[/bold cyan]")
    console.print("[bold cyan]   AI Heuristic Code Review Agent MVP Started    [/bold cyan]")
    console.print("[bold cyan]=================================================[/bold cyan]\n")

def run(entry_file: str, intent: str):
    print_banner()
    
    initial_state = AgentState(
        entry_file=entry_file,
        user_intent=intent
    )
    
    console.print(f"[yellow]Entry File:[/yellow] {entry_file}")
    console.print(f"[yellow]User Intent:[/yellow] {intent}\n")
    
    graph = build_graph()
    
    console.print("[bold green]Running Pipeline...[/bold green]\n")
    
    final_state = None
    try:
        for s in graph.stream(initial_state, {"recursion_limit": 50}):
            node_name = list(s.keys())[0]
            console.print(f"[dim]✓ Node executed: {node_name}[/dim]")
            final_state = s[node_name]
    except Exception as e:
        console.print(f"[bold red]Pipeline Error:[/bold red] {e}")
        return

    if final_state is None:
        console.print("[red]No state returned from graph.[/red]")
        return
        
    console.print("\n[bold cyan]=================================================[/bold cyan]")
    console.print("[bold cyan]             Code Review Report                  [/bold cyan]")
    console.print("[bold cyan]=================================================[/bold cyan]\n")
    
    tasks = final_state.get("tasks", [])
    if not tasks:
        console.print("No tasks generated by Intention Analyzer.")
        return
        
    for task in tasks:
        console.print(Panel(f"[bold magenta]Task: {task.id}[/bold magenta]", expand=False))
        console.print("[bold yellow]🎯 Intention:[/bold yellow]")
        console.print(task.intention + "\n")
        
        console.print("[bold yellow]🔍 Discovered Implementation:[/bold yellow]")
        console.print(Markdown(task.implementation_path))
        console.print("\n")
        
        console.print("[bold yellow]🛠️ Ground Reviewer:[/bold yellow]")
        console.print(Markdown(task.code_review))
        console.print("\n")
        
        console.print("[bold yellow]⚔️ Intention Attacker:[/bold yellow]")
        console.print(Markdown(task.attacker_review))
        console.print("\n" + "-"*50 + "\n")

def main():
    # Read defaults from config.toml [review] section
    review_cfg = get_review_config()
    
    parser = argparse.ArgumentParser(description="AI Code Reviewer MVP")
    parser.add_argument("--entry", default=review_cfg.get("entry_file", ""),
                        help="Path to the entry file (default: from config.toml)")
    parser.add_argument("--intent", default=review_cfg.get("intent", ""),
                        help="Description of the business intent (default: from config.toml)")
    
    args = parser.parse_args()
    
    if not args.entry or not args.intent:
        console.print("[bold red]Error:[/bold red] --entry and --intent are required (via CLI args or config.toml [review] section)")
        sys.exit(1)
    
    run(args.entry, args.intent)

if __name__ == "__main__":
    main()
