"""
Pipeline — 使用 TaskQueue 编排的多阶段 Code Review 流水线

流程:
  Phase 1: Intention → 拆分子任务
  Phase 2: Implement × N → 探索实现 (并行, 可迭代)
  Phase 2.5: Gap Analyzer → 查漏补缺 + 去重 → 可能 spawn 新 Implement
  Phase 3: Review + Attack × N → 代码审查 + 逻辑攻击 (并行)
"""

from __future__ import annotations

import json
import os
from typing import Optional

from core.backend import Backend
from core.agent import Agent
from core.task import Task, TaskContext, TaskResult
from core.task_queue import TaskQueue
from core.config import get_temperature
from core.progress import ProgressTracker
from agents.prompts import (
    INTENTION_SYSTEM_PROMPT,
    IMPLEMENTATION_SYSTEM_PROMPT,
    REVIEWER_SYSTEM_PROMPT,
    ATTACKER_SYSTEM_PROMPT,
    GAP_ANALYZER_SYSTEM_PROMPT,
)


class ReviewPipeline:
    """
    Code Review 流水线

    Phase 1: intention_analyze    → 拆分子任务
    Phase 2: implement_<id> × N  → 探索实现 (并行)
    Phase 2.5: gap_analyzer       → 查漏 + 去重 → spawn 新 implement (可迭代)
    Phase 3: review_<id> + attack_<id> × N → 审查 + 攻击 (并行)
    """

    def __init__(
        self,
        backend: Backend,
        project_root: str,
        max_concurrency: int = 4,
        max_gap_rounds: int = 2,
        output_dir: str = "",
        on_task_start=None,
        on_task_done=None,
    ):
        self.backend = backend
        self.project_root = project_root
        self.max_concurrency = max_concurrency
        self.max_gap_rounds = max_gap_rounds
        self.output_dir = output_dir
        self.on_task_start = on_task_start
        self.on_task_done = on_task_done

        if self.output_dir:
            os.makedirs(self.output_dir, exist_ok=True)

        # 断点续跑: 加载已有进度
        self.progress = ProgressTracker(self.output_dir)

    def run(self, entry_file: str, user_intent: str) -> PipelineResult:
        """运行完整的 Code Review 流水线"""
        self.progress.init_run(entry_file, user_intent)

        # 检查是否有已保存的进度
        resumed_tasks = self.progress.get_sub_tasks()
        if resumed_tasks:
            self._notify(f"  [cyan]↻ Resuming from checkpoint ({self.progress.summary()})[/cyan]")

        # ── Phase 1: Intention ── #
        if self.progress.is_done("intention") and resumed_tasks:
            intention_result = self.progress.load_result("intention", self.output_dir)
            if intention_result:
                self._notify("  [dim]⏭ Skipping intention (cached)[/dim]")
            else:
                intention_result = self._run_intention(entry_file, user_intent)
        else:
            intention_result = self._run_intention(entry_file, user_intent)

        sub_tasks = resumed_tasks or self._parse_intention_tasks(intention_result.report, user_intent)
        self.progress.save_sub_tasks(sub_tasks)

        if not sub_tasks:
            return PipelineResult(
                tasks=[], intention_result=intention_result,
                results={}, summary="No tasks generated by Intention Analyzer.",
            )

        # ── Phase 2 + 2.5: Implement → Gap Analyze → Re-implement (iterative) ── #
        all_impl_results = {}
        all_sub_tasks = list(sub_tasks)

        for gap_round in range(self.max_gap_rounds + 1):
            # Run implements for current batch
            new_results = self._run_implements(
                sub_tasks, entry_file, user_intent,
                round_num=gap_round,
            )
            all_impl_results.update(new_results)

            # Gap Analysis (skip on last round)
            if gap_round < self.max_gap_rounds:
                gap_result = self._run_gap_analyzer(
                    all_sub_tasks, all_impl_results, entry_file, user_intent,
                    round_num=gap_round,
                )

                new_tasks, duplicates = self._parse_gap_result(gap_result.report)

                # Handle duplicates
                for dup in duplicates:
                    remove_id = dup.get("remove", "")
                    if remove_id:
                        self._notify(f"  [dim]🔄 Dedup: removing {remove_id} (duplicate of {dup.get('keep', '')})[/dim]")

                if not new_tasks:
                    self._notify(f"  [green]✓ Gap Analyzer (round {gap_round + 1}): no gaps found, proceeding to review[/green]")
                    break

                self._notify(f"  [yellow]⟳ Gap Analyzer (round {gap_round + 1}): found {len(new_tasks)} gaps, spawning new implements[/yellow]")
                sub_tasks = new_tasks
                all_sub_tasks.extend(new_tasks)
            else:
                self._notify(f"  [dim]Max gap rounds ({self.max_gap_rounds}) reached, proceeding to review[/dim]")

        # ── Phase 3: Review + Attack ── #
        review_attack_results = self._run_review_attack(
            all_sub_tasks, all_impl_results, entry_file, user_intent,
        )

        # ── Assemble Results ── #
        all_results = {**all_impl_results, **review_attack_results}
        task_reports = self._build_reports(all_sub_tasks, all_results)

        return PipelineResult(
            tasks=task_reports,
            intention_result=intention_result,
            results=all_results,
            summary=self._build_summary(all_results),
        )

    # ───────────── Phase Runners ───────────── #

    def _run_intention(self, entry_file: str, user_intent: str) -> TaskResult:
        """Phase 1: Intention Analyzer — 带工具自由探索项目"""
        agent = Agent(
            role="intention_analyzer",
            system_prompt=INTENTION_SYSTEM_PROMPT,
            backend=self.backend,
            tools=["tree", "find", "cat", "grep"],
            output_format="json",
            temperature=get_temperature("intention"),
            max_steps=20,
        )

        # 构造 prompt: entry_file 可选
        prompt_parts = [f"User Intent: {user_intent}"]
        if entry_file:
            prompt_parts.append(f"Entry File: {entry_file}")
        prompt_parts.append(f"Project Root: {self.project_root}")

        task = Task(
            task_id="intention",
            agent=agent,
            context=TaskContext(
                entry_file=entry_file,
                user_intent=user_intent,
                project_root=self.project_root,
            ),
            prompt_builder=lambda ctx, p="\n".join(prompt_parts): p,
            use_tools=True,
        )
        if self.on_task_start:
            self.on_task_start("intention")
        result = task.execute()
        if self.on_task_done:
            self.on_task_done("intention", result)
        self._save_intermediate("intention", result)
        self.progress.mark_done("intention", result)
        return result

    def _run_implements(
        self,
        sub_tasks: list[dict],
        entry_file: str,
        user_intent: str,
        round_num: int = 0,
    ) -> dict[str, TaskResult]:
        """Phase 2: Run implement tasks in parallel (skip cached)"""
        queue = TaskQueue(max_concurrency=self.max_concurrency)
        cached_results = {}

        for st in sub_tasks:
            tid = st["id"]
            task_id = f"implement_{tid}"

            # 断点续跑: 跳过已完成的
            if self.progress.is_done(task_id):
                cached = self.progress.load_result(task_id, self.output_dir)
                if cached:
                    self._notify(f"  [dim]⏭ {task_id} (cached)[/dim]")
                    cached_results[task_id] = cached
                    continue

            agent = Agent(
                role="implementation_analyzer",
                system_prompt=IMPLEMENTATION_SYSTEM_PROMPT,
                backend=self.backend,
                tools=["cat", "grep", "find", "tree"],
                temperature=get_temperature("implementation"),
                max_steps=15,
            )
            task = Task(
                task_id=task_id,
                agent=agent,
                context=TaskContext(
                    entry_file=entry_file,
                    user_intent=user_intent,
                    project_root=self.project_root,
                    extra={"task_intention": st["intention"]},
                ),
                use_tools=True,
            )
            queue.add(task)

        new_results = {}
        if queue._tasks:  # 有未完成的 task
            new_results = queue.run_all(
                on_task_start=self.on_task_start,
                on_task_done=self._make_save_callback(),
            )

        return {**cached_results, **new_results}

    def _run_gap_analyzer(
        self,
        all_sub_tasks: list[dict],
        impl_results: dict[str, TaskResult],
        entry_file: str,
        user_intent: str,
        round_num: int = 0,
    ) -> TaskResult:
        """Phase 2.5: Gap Analyzer — 查漏补缺 + 去重"""

        # 构造 gap analyzer 的输入: 所有 implement 报告的摘要
        summaries = []
        for st in all_sub_tasks:
            tid = st["id"]
            impl = impl_results.get(f"implement_{tid}")
            if impl:
                summaries.append(
                    f"## Task: {tid}\n"
                    f"**Intention:** {st['intention']}\n"
                    f"**Status:** {impl.status}\n"
                    f"**Report (first 1000 chars):**\n{impl.report[:1000]}\n"
                )

        gap_prompt = (
            f"Entry File: {entry_file}\n"
            f"User Intent: {user_intent}\n"
            f"Round: {round_num + 1}\n\n"
            f"## Existing Implementation Reports\n\n"
            + "\n---\n".join(summaries)
        )

        agent = Agent(
            role="gap_analyzer",
            system_prompt=GAP_ANALYZER_SYSTEM_PROMPT,
            backend=self.backend,
            output_format="json",
            temperature=get_temperature("intention"),  # 用 intention 的温度
        )
        task = Task(
            task_id=f"gap_analysis_round_{round_num + 1}",
            agent=agent,
            context=TaskContext(
                entry_file=entry_file,
                user_intent=user_intent,
                project_root=self.project_root,
            ),
            prompt_builder=lambda ctx, p=gap_prompt: p,  # 直接用构造的 prompt
        )

        if self.on_task_start:
            self.on_task_start(task.task_id)
        result = task.execute()
        if self.on_task_done:
            self.on_task_done(task.task_id, result)
        self._save_intermediate(task.task_id, result)
        return result

    def _run_review_attack(
        self,
        all_sub_tasks: list[dict],
        impl_results: dict[str, TaskResult],
        entry_file: str,
        user_intent: str,
    ) -> dict[str, TaskResult]:
        """Phase 3: Review + Attack in parallel (skip cached)"""
        queue = TaskQueue(max_concurrency=self.max_concurrency)
        cached_results = {}

        for st in all_sub_tasks:
            tid = st["id"]
            impl_report = impl_results.get(f"implement_{tid}")
            if not impl_report or impl_report.status != "success":
                continue

            upstream = {"implementation_report": impl_report.report}

            for prefix, agent_role, prompt in [
                ("review", "ground_reviewer", REVIEWER_SYSTEM_PROMPT),
                ("attack", "intention_attacker", ATTACKER_SYSTEM_PROMPT),
            ]:
                task_id = f"{prefix}_{tid}"

                # 断点续跑: 跳过已完成的
                if self.progress.is_done(task_id):
                    cached = self.progress.load_result(task_id, self.output_dir)
                    if cached:
                        self._notify(f"  [dim]⏭ {task_id} (cached)[/dim]")
                        cached_results[task_id] = cached
                        continue

                temp_key = "reviewer" if prefix == "review" else "attacker"
                agent = Agent(
                    role=agent_role,
                    system_prompt=prompt,
                    backend=self.backend,
                    temperature=get_temperature(temp_key),
                )
                task = Task(
                    task_id=task_id,
                    agent=agent,
                    context=TaskContext(
                        entry_file=entry_file,
                        user_intent=user_intent,
                        project_root=self.project_root,
                        extra={"task_intention": st["intention"]},
                        upstream_results=upstream,
                    ),
                )
                queue.add(task)

        new_results = {}
        if queue._tasks:
            new_results = queue.run_all(
                on_task_start=self.on_task_start,
                on_task_done=self._make_save_callback(),
            )

        return {**cached_results, **new_results}

    # ───────────── Helpers ───────────── #

    def _make_save_callback(self):
        """包装 on_task_done 以保存中间报告 + 更新进度"""
        def _on_done(task_id, result):
            self._save_intermediate(task_id, result)
            self.progress.mark_done(task_id, result)
            if self.on_task_done:
                self.on_task_done(task_id, result)
        return _on_done

    def _notify(self, message: str):
        """输出状态消息（如果有回调）"""
        # 直接打印，因为 Rich 需要 console
        try:
            from rich.console import Console
            Console().print(message)
        except ImportError:
            print(message)

    def _parse_intention_tasks(self, report: str, fallback_intent: str) -> list[dict]:
        """解析 intention agent 输出的 JSON 任务列表 (容忍 preamble 文字)"""
        import re
        text = report.replace("```json", "").replace("```", "").strip()

        # 尝试直接解析
        try:
            parsed = json.loads(text)
            if isinstance(parsed, list):
                return [{"id": pt.get("id", f"task_{i+1}"), "intention": pt.get("intention", "")}
                        for i, pt in enumerate(parsed)]
        except (json.JSONDecodeError, TypeError):
            pass

        # 尝试从混合文本中提取 JSON 数组
        match = re.search(r'\[[\s\S]*\]', text)
        if match:
            try:
                parsed = json.loads(match.group())
                if isinstance(parsed, list):
                    return [{"id": pt.get("id", f"task_{i+1}"), "intention": pt.get("intention", "")}
                            for i, pt in enumerate(parsed)]
            except (json.JSONDecodeError, TypeError):
                pass

        return [{"id": "fallback", "intention": fallback_intent}]

    def _parse_gap_result(self, report: str) -> tuple[list[dict], list[dict]]:
        """解析 gap analyzer 输出: (new_tasks, duplicates)"""
        import re
        text = report.replace("```json", "").replace("```", "").strip()

        # 尝试直接解析
        parsed = None
        try:
            parsed = json.loads(text)
        except (json.JSONDecodeError, TypeError):
            # 尝试从混合文本提取 JSON object
            match = re.search(r'\{[\s\S]*\}', text)
            if match:
                try:
                    parsed = json.loads(match.group())
                except (json.JSONDecodeError, TypeError):
                    pass

        if isinstance(parsed, dict):
            gaps = parsed.get("gaps", [])
            duplicates = parsed.get("duplicates", [])
            new_tasks = [
                {"id": g["id"], "intention": g["intention"]}
                for g in gaps if "id" in g and "intention" in g
            ]
            return new_tasks, duplicates
        return [], []

    def _build_reports(self, sub_tasks: list[dict], all_results: dict) -> list:
        """组装 TaskReport 列表"""
        reports = []
        empty = TaskResult(task_id="", agent_role="")
        for st in sub_tasks:
            tid = st["id"]
            reports.append(TaskReport(
                task_id=tid,
                intention=st["intention"],
                implementation=all_results.get(f"implement_{tid}", empty).report,
                code_review=all_results.get(f"review_{tid}", empty).report,
                attack_review=all_results.get(f"attack_{tid}", empty).report,
                impl_steps=all_results.get(f"implement_{tid}", empty).steps,
                impl_files=all_results.get(f"implement_{tid}", empty).files_accessed,
            ))
        return reports

    def _build_summary(self, all_results: dict) -> str:
        """生成执行摘要"""
        lines = ["## Execution Summary\n"]
        total_ms = 0
        for tid, r in all_results.items():
            icon = "✅" if r.status == "success" else "❌"
            lines.append(f"- {icon} **{tid}** ({r.agent_role}) — {r.duration_ms}ms, {len(r.steps)} steps")
            total_ms += r.duration_ms
        lines.append(f"\n**Total**: {len(all_results)} tasks, {total_ms}ms")
        return "\n".join(lines)

    def _save_intermediate(self, task_id: str, result: TaskResult):
        """将单个 task 中间报告保存为文件"""
        if not self.output_dir:
            return

        filepath = os.path.join(self.output_dir, f"{task_id}.md")

        lines = [
            f"# {task_id}",
            f"\n- **Agent**: {result.agent_role}",
            f"- **Status**: {result.status}",
            f"- **Duration**: {result.duration_ms}ms",
            f"- **Steps**: {len(result.steps)}",
        ]
        if result.files_accessed:
            lines.append(f"- **Files**: {', '.join(result.files_accessed)}")
        if result.error:
            lines.append(f"- **Error**: {result.error}")

        lines.append(f"\n## Report\n\n{result.report}")

        if result.steps:
            lines.append("\n## Step Logs\n")
            lines.append("| Step | Action | Input | Output | Duration |")
            lines.append("|------|--------|-------|--------|----------|")
            for s in result.steps:
                lines.append(
                    f"| {s.get('step','')} | {s.get('action','')} "
                    f"| {s.get('input','')[:60]} | {s.get('output','')[:60]} "
                    f"| {s.get('duration_ms',0)}ms |"
                )

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines) + '\n')


class TaskReport:
    """单个子任务的完整审查报告"""

    def __init__(
        self,
        task_id: str,
        intention: str,
        implementation: str = "",
        code_review: str = "",
        attack_review: str = "",
        impl_steps: list = None,
        impl_files: list = None,
    ):
        self.task_id = task_id
        self.intention = intention
        self.implementation = implementation
        self.code_review = code_review
        self.attack_review = attack_review
        self.impl_steps = impl_steps or []
        self.impl_files = impl_files or []


class PipelineResult:
    """完整流水线的执行结果"""

    def __init__(
        self,
        tasks: list[TaskReport],
        intention_result: TaskResult,
        results: dict[str, TaskResult],
        summary: str = "",
    ):
        self.tasks = tasks
        self.intention_result = intention_result
        self.results = results
        self.summary = summary

    def to_markdown(self, verbose: bool = False) -> str:
        """生成完整的 Markdown 报告"""
        lines = []
        lines.append("# Code Review Report\n")

        # 概览
        lines.append("## Overview\n")
        lines.append(f"- **Tasks analyzed**: {len(self.tasks)}")
        total_files = set()
        for t in self.tasks:
            total_files.update(t.impl_files)
        lines.append(f"- **Files explored**: {len(total_files)}")
        lines.append("")

        if self.summary:
            lines.append(self.summary)
            lines.append("")

        # 分 Task 报告
        for task in self.tasks:
            lines.append(f"---\n\n## [{task.task_id}] {task.intention[:80]}\n")

            lines.append("### 🎯 Intention\n")
            lines.append(task.intention)
            lines.append("")

            lines.append("### 🔍 Discovered Implementation\n")
            lines.append(task.implementation or "_No implementation found._")
            lines.append("")

            lines.append("### 🛠️ Ground Review\n")
            lines.append(task.code_review or "_No review generated._")
            lines.append("")

            lines.append("### ⚔️ Intention Attacker\n")
            lines.append(task.attack_review or "_No attack generated._")
            lines.append("")

            if verbose and task.impl_steps:
                lines.append("### 📋 Exploration Steps\n")
                lines.append("| Step | Action | Input | Duration |")
                lines.append("|------|--------|-------|----------|")
                for step in task.impl_steps:
                    lines.append(
                        f"| {step.get('step', '')} | {step.get('action', '')} "
                        f"| {step.get('input', '')[:60]} | {step.get('duration_ms', 0)}ms |"
                    )
                lines.append("")

            if task.impl_files:
                lines.append("### 📁 Files Accessed\n")
                for f in task.impl_files:
                    lines.append(f"- `{f}`")
                lines.append("")

        return "\n".join(lines)
