/**
 * @coacker/brain/audit — AuditBrain 状态机
 *
 * Brain 是决策者：驱动审查流程，管理状态，委托任务构造/解析/持久化给子模块。
 *
 * 流程:
 *   Phase 1:   Intention → 探索项目 → 拆分子任务
 *   Phase 2:   对每个子任务 → 构造 4-step Task (implement → review → attack → propose_issues)
 *   Phase 2.5: Gap Analysis → 查漏补缺 (可选迭代)
 *   Phase 3:   Consolidation → AI 汇总报告
 */

import type { Player } from "@coacker/player";
import type { TaskResult } from "@coacker/shared";
import { Logger } from "@coacker/shared";

import type {
  SubTask,
  TaskReport,
  AuditReport,
  AuditPhase,
  AuditBrainOptions,
} from "./types.js";
import {
  buildIntentionTask,
  buildSubTask,
  buildGapTask,
  buildConsolidationTask,
} from "./task-builder.js";
import { buildLocalTasks } from "./local-task-builder.js";
import {
  getFirstResponse,
  extractReport,
  parseIntentionTasks,
  parseGapResult,
} from "./result-parser.js";
import {
  ensureOutputDirs,
  persistState,
  persistIntention,
  persistReport,
  persistConversation,
  persistMarkdownReport,
  loadState,
  loadIntention,
  loadReports,
} from "./persister.js";
import { buildReport } from "./report-builder.js";

// Re-export as Brain for backward compatibility
export { type AuditBrainOptions as BrainOptions };

export class AuditBrain {
  // ── 配置 ──
  private readonly maxGapRounds: number;
  private readonly maxSubTasks: number;
  private readonly entryFile: string;
  private readonly auditPaths: string[];
  private readonly userIntent: string;
  private readonly projectRoot: string;
  private readonly outputDir: string;
  private readonly origin: string;

  // ── 状态机 ──
  private _phase: AuditPhase = "idle";
  private subtasks: SubTask[] = [];
  private reports: Map<string, TaskReport> = new Map();
  private gapRound = 0;

  // ── 历史 ──
  private _history: TaskResult[] = [];

  private log: Logger;

  constructor(options: AuditBrainOptions) {
    this.maxGapRounds = options.audit.maxGapRounds;
    this.maxSubTasks = options.audit.maxSubTasks;
    this.entryFile = options.project.entry;
    this.auditPaths = options.project.auditPaths || [];
    this.userIntent = options.project.intent;
    this.projectRoot = options.project.root;
    this.outputDir = options.output.dir;
    this.origin = options.project.origin;
    this.log = new Logger("brain");

    ensureOutputDirs(this.outputDir);
  }

  /** 当前阶段 */
  get phase(): AuditPhase {
    return this._phase;
  }

  /** 所有任务执行历史 */
  get history(): readonly TaskResult[] {
    return this._history;
  }

  /**
   * 运行完整的审查流程
   */
  async run(player: Player): Promise<AuditReport> {
    this.log.info("▶ Brain starting audit");

    // ── 检查是否可恢复 ──
    const savedState = loadState(this.outputDir);
    if (
      savedState &&
      savedState.phase !== "idle" &&
      savedState.phase !== "done"
    ) {
      this.log.info(
        `♻ Found resumable state: phase=${savedState.phase}, ` +
          `gapRound=${savedState.gapRound}, ` +
          `subtasks=${savedState.subtasks.length}`,
      );
      return this.resume(player, savedState);
    }

    // ── Phase 1: Intention ──
    this._phase = "intention";
    this.log.info("── Phase 1: Intention Analysis ──");

    if (this.auditPaths.length > 0) {
      // 本地生成 — 跳过 AI
      this.subtasks = buildLocalTasks(this.projectRoot, this.auditPaths, this.userIntent);
      this.log.info(`  📋 ${this.subtasks.length} local tasks generated from auditPaths`);
    } else {
      const intentionTask = buildIntentionTask(this.entryFile, this.userIntent);
      const intentionResult = await player.executeTask(intentionTask);
      this._history.push(intentionResult);
      this.persist(intentionTask, intentionResult);

      const intentionResponse = getFirstResponse(intentionResult);
      this.subtasks = parseIntentionTasks(
        intentionResponse,
        this.userIntent,
      ).slice(0, this.maxSubTasks);

      this.log.info(`  📋 ${this.subtasks.length} AI-generated sub-tasks identified`);
    }

    persistIntention(this.outputDir, this.subtasks);
    this.persistCurrentState();

    if (this.subtasks.length === 0) {
      this._phase = "done";
      this.persistCurrentState();
      return buildReport([], "No tasks generated by Intention Analyzer.");
    }

    // ── Phase 2: Execution ──
    this._phase = "execution";
    this.log.info(
      `── Phase 2: Execution (${this.subtasks.length} tasks, budget ${this.maxSubTasks}/${this.maxSubTasks}) ──`,
    );

    for (const st of this.subtasks) {
      await this.executeSubTask(st, player);
    }

    // ── Phase 2.5 + 3: Gap Analysis + Consolidation ──
    return this.finalize(player);
  }

  // ─── Private Helpers ───────────────────────────

  /**
   * 执行单个 subtask (with checkpoint tracking)
   *
   * 状态迁移: pending → in_progress(sent → responded) → done
   */
  private async executeSubTask(st: SubTask, player: Player): Promise<void> {
    st.status = "in_progress";
    persistIntention(this.outputDir, this.subtasks);

    const task = buildSubTask(
      st,
      this.entryFile,
      this.userIntent,
      this.origin,
      this.reports,
    );

    st.completedSteps = [];

    const result = await player.executeTask(task, {
      onStepStart: ({ stepId, stepIndex, totalSteps, conversationId }) => {
        // 设置 checkpoint: sent
        st.conversationId = conversationId;
        st.currentStep = stepId;
        st.stepProgress = `${stepIndex + 1}/${totalSteps}`;
        st.checkpoint = {
          chat_status: "sent",
          chat_type: stepId,
          chat_input: task.steps[stepIndex].message,
          conversation_title: null, // 尚未收到回复，无法获取 title
        };
        persistIntention(this.outputDir, this.subtasks);
        this.persistCurrentState();
      },
      onStepEnd: async ({ stepId, conversationId: _conversationId }) => {
        // 设置 checkpoint: responded + 获取对话标题
        if (st.checkpoint) {
          st.checkpoint.chat_status = "responded";
          // 获取对话标题 (用于断点续传时切回对话)
          try {
            const title = await player.backend.getConversationTitle();
            st.checkpoint.conversation_title = title;
          } catch {
            // ignore — title is best-effort
          }
        }
        st.completedSteps = [...(st.completedSteps ?? []), stepId];
        persistIntention(this.outputDir, this.subtasks);
        this.persistCurrentState();
      },
    });

    this._history.push(result);

    const report = extractReport(st, result);
    this.reports.set(st.id, report);

    // 标记 done, 清除运行时字段
    st.status = "done";
    st.conversationId = result.conversationId;
    delete st.checkpoint;
    delete st.currentStep;
    delete st.stepProgress;

    this.persist(task, result);
    persistReport(this.outputDir, st.id, report);
    persistIntention(this.outputDir, this.subtasks);
    this.persistCurrentState();

    this.log.info(
      `  📋 [${st.id}] done — impl: ${report.implementation.length}c, ` +
        `review: ${report.codeReview.length}c, attack: ${report.attackReview.length}c`,
    );
  }

  /**
   * 从断点恢复审查流程
   */
  private async resume(
    player: Player,
    savedState: import("./types.js").AuditBrainState,
  ): Promise<AuditReport> {
    // 恢复内部状态
    this._phase = savedState.phase;
    this.gapRound = savedState.gapRound;

    const savedIntention = loadIntention(this.outputDir);
    if (savedIntention) {
      this.subtasks = savedIntention;
    }

    this.reports = loadReports(this.outputDir);

    this.log.info(
      `  ♻ Restored: phase=${this._phase}, ` +
        `subtasks=${this.subtasks.length} (done=${this.subtasks.filter((s) => s.status === "done").length}), ` +
        `reports=${this.reports.size}`,
    );

    // 处理 in_progress 的 subtask
    const inProgress = this.subtasks.find((s) => s.status === "in_progress");
    if (inProgress?.checkpoint) {
      const cp = inProgress.checkpoint;
      this.log.info(
        `  ♻ Resuming subtask [${inProgress.id}] — ` +
          `chat_status=${cp.chat_status}, chat_type=${cp.chat_type}`,
      );

      if (cp.chat_status === "sent") {
        // prompt 已发, 等 AI 回复
        if (cp.conversation_title) {
          await player.backend.switchToConversation(cp.conversation_title);
        }
        const waitResult = await player.waitForResponse();
        this.log.info(
          `  ♻ waitForResponse: state=${waitResult.state}, elapsed=${waitResult.elapsed.toFixed(1)}s`,
        );

        // 收到回复后标记 responded
        inProgress.checkpoint!.chat_status = "responded";
        inProgress.completedSteps = [
          ...(inProgress.completedSteps ?? []),
          cp.chat_type,
        ];
        persistIntention(this.outputDir, this.subtasks);

        // 继续执行剩余 steps
        const task = buildSubTask(
          inProgress,
          this.entryFile,
          this.userIntent,
          this.origin,
          this.reports,
        );
        const completedCount = inProgress.completedSteps?.length ?? 0;

        if (completedCount < task.steps.length) {
          const result = await player.continueTask(
            task,
            completedCount,
            inProgress.conversationId ?? `resumed_${inProgress.id}`,
          );
          this._history.push(result);

          // 把 waitResult 的 snapshot 注入到已完成步骤的结果里
          // (continueTask 的前 N 步标记为 skipped, 但 waitResult 有当前步骤的真实数据)
          const waitStepIndex = completedCount - 1;
          if (waitStepIndex >= 0 && waitStepIndex < result.stepResults.length) {
            result.stepResults[waitStepIndex] = {
              ...result.stepResults[waitStepIndex],
              snapshot: waitResult.snapshot,
              status: waitResult.state === "done" ? "success" : "error",
              elapsed: waitResult.elapsed,
            };
          }

          const report = extractReport(inProgress, result);
          this.reports.set(inProgress.id, report);
          persistReport(this.outputDir, inProgress.id, report);
        }

        // 标记 done
        inProgress.status = "done";
        delete inProgress.checkpoint;
        delete inProgress.currentStep;
        delete inProgress.stepProgress;
        persistIntention(this.outputDir, this.subtasks);
        this.persistCurrentState();

        this.log.info(`  ✅ Resumed subtask [${inProgress.id}] completed`);
      } else if (cp.chat_status === "responded") {
        // 上一步收到回复了, 继续发下一步
        if (cp.conversation_title) {
          await player.backend.switchToConversation(cp.conversation_title);
        }

        const task = buildSubTask(
          inProgress,
          this.entryFile,
          this.userIntent,
          this.origin,
          this.reports,
        );
        const completedCount = inProgress.completedSteps?.length ?? 0;

        const result = await player.continueTask(
          task,
          completedCount,
          inProgress.conversationId ?? `resumed_${inProgress.id}`,
        );
        this._history.push(result);

        const report = extractReport(inProgress, result);
        this.reports.set(inProgress.id, report);

        inProgress.status = "done";
        delete inProgress.checkpoint;
        delete inProgress.currentStep;
        delete inProgress.stepProgress;
        persistReport(this.outputDir, inProgress.id, report);
        persistIntention(this.outputDir, this.subtasks);
        this.persistCurrentState();

        this.log.info(`  ✅ Resumed subtask [${inProgress.id}] completed`);
      }
    }

    // 执行剩余 pending subtasks
    const remaining = this.subtasks.filter((s) => s.status === "pending");
    if (remaining.length > 0) {
      this.log.info(
        `  ♻ ${remaining.length} pending subtasks remain, continuing execution`,
      );
      this._phase = "execution";
      for (const st of remaining) {
        await this.executeSubTask(st, player);
      }
    }

    // Gap analysis + consolidation (从当前 gapRound 继续)
    return this.finalize(player);
  }

  /**
   * 执行 Gap Analysis + Consolidation 并返回报告
   * (共用于 run() 和 resume())
   */
  private async finalize(player: Player): Promise<AuditReport> {
    // Gap analysis loop (每轮递增 gapRound)
    while (this.gapRound < this.maxGapRounds) {
      const remainingBudget = this.maxSubTasks - this.reports.size;
      if (remainingBudget <= 0) {
        this.log.info(
          `  ✓ Task budget exhausted (${this.reports.size}/${this.maxSubTasks}), skipping gap analysis`,
        );
        break;
      }

      this._phase = "gap_analysis";
      this.log.info(
        `── Phase 2.5: Gap Analysis (round ${this.gapRound + 1}, budget: ${remainingBudget}) ──`,
      );

      const gapTask = buildGapTask(
        this.gapRound,
        this.entryFile,
        this.userIntent,
        this.reports,
      );
      const gapResult = await player.executeTask(gapTask);
      this._history.push(gapResult);
      this.persist(gapTask, gapResult);

      const gapResponse = getFirstResponse(gapResult);
      const newTasks = parseGapResult(gapResponse).slice(0, remainingBudget);

      this.gapRound++; // ← fix: 递增 gapRound
      this.persistCurrentState();

      if (newTasks.length === 0) {
        this.log.info("  ✓ No gaps found, done");
        break;
      }

      this.log.info(`  ⟳ Found ${newTasks.length} gaps, executing...`);
      this.subtasks.push(...newTasks);
      this._phase = "execution";
      for (const st of newTasks) {
        await this.executeSubTask(st, player);
      }
    }

    // Consolidation
    this._phase = "consolidation";
    this.log.info("── Phase 3: Consolidation ──");

    const consolTask = buildConsolidationTask(this.userIntent, this.reports);
    const consolResult = await player.executeTask(consolTask);
    this._history.push(consolResult);
    this.persist(consolTask, consolResult);

    const executiveSummary = getFirstResponse(consolResult);
    if (
      consolResult.status === "success" ||
      consolResult.status === "partial"
    ) {
      this.log.info(
        `  ✅ Consolidation done (${executiveSummary.length} chars)`,
      );
    } else {
      this.log.warn(`  ⚠️ Consolidation failed`);
    }

    this._phase = "done";
    const taskReports = Array.from(this.reports.values());
    const report = buildReport(taskReports, undefined, executiveSummary);

    this.persistCurrentState();
    persistMarkdownReport(this.outputDir, report);
    this.log.info(
      `✅ Brain finished. ${this.reports.size} tasks analyzed, ${this._history.length} total executions.`,
    );
    return report;
  }

  /** 持久化对话 + 状态 (每步执行后调用) */
  private persist(
    task: Parameters<typeof persistConversation>[1],
    result: TaskResult,
  ): void {
    persistConversation(this.outputDir, task, result);
    this.persistCurrentState();
  }

  /** 持久化当前状态快照 */
  private persistCurrentState(): void {
    persistState(
      this.outputDir,
      this._phase,
      this.gapRound,
      this.subtasks,
      this.reports,
      this._history,
    );
  }
}
