/**
 * @coacker/brain — 审查流水线
 *
 * 编排 Code Review:
 *   Phase 1:   Intention → 拆分子任务
 *   Phase 2:   对每个子任务 → 一个对话内依次执行 Implement → Review → Attack
 *   Phase 2.5: Gap Analysis → 查漏补缺 (可选迭代)
 *
 * 每个子任务 = 一个 IDE 对话:
 *   开新对话 → Implement (第一条消息)
 *            → Review (follow-up, 同一对话)
 *            → Attack (follow-up, 同一对话)
 *
 * 执行全部通过 Player.executeTask()，Brain 只做编排。
 */

import type { Player } from '@coacker/player';
import type { Task, TaskResult, CoasterEvents } from '@coacker/shared';
import { Logger } from '@coacker/shared';
import { extractJSON } from '@coacker/player';

import type {
  AuditPipelineOptions,
  SubTask,
  TaskReport,
  GapResult,
  AuditReport,
} from './types.js';

import {
  INTENTION_SYSTEM_PROMPT,
  IMPLEMENTATION_SYSTEM_PROMPT,
  REVIEWER_SYSTEM_PROMPT,
  ATTACKER_SYSTEM_PROMPT,
  GAP_ANALYZER_SYSTEM_PROMPT,
} from './prompts.js';

export class AuditPipeline {
  private maxGapRounds: number;
  private maxSubTasks: number;
  private events: CoasterEvents;
  private log: Logger;

  constructor(options: AuditPipelineOptions = {}) {
    this.maxGapRounds = options.audit?.maxGapRounds ?? 2;
    this.maxSubTasks = options.audit?.maxSubTasks ?? 20;
    this.events = options.events ?? {};
    this.log = new Logger('audit');
  }

  /**
   * 运行完整的审查流水线
   */
  async run(
    player: Player,
    entryFile: string,
    userIntent: string,
  ): Promise<AuditReport> {
    this.log.info('▶ Audit pipeline starting');

    // ── Phase 1: Intention (独立对话) ──
    this.log.info('── Phase 1: Intention Analysis ──');
    const intentionResult = await this.runIntention(player, entryFile, userIntent);
    const subTasks = this.parseIntentionTasks(intentionResult.response, userIntent)
      .slice(0, this.maxSubTasks);
    this.log.info(`  📋 ${subTasks.length} sub-tasks identified`);

    if (subTasks.length === 0) {
      return this.buildReport([], 'No tasks generated by Intention Analyzer.');
    }

    // ── Phase 2 + 2.5: 每个子任务在一个对话里 implement → review → attack ──
    const allTaskReports: TaskReport[] = [];
    let allSubTasks = [...subTasks];
    let currentBatch = subTasks;

    for (let round = 0; round <= this.maxGapRounds; round++) {
      this.log.info(`── Phase 2: Implement + Review + Attack (round ${round + 1}, ${currentBatch.length} tasks) ──`);

      for (const st of currentBatch) {
        const report = await this.runSubTask(player, st, entryFile, userIntent);
        allTaskReports.push(report);
        this.log.info(`  📋 [${st.id}] done — impl: ${report.implementation.length}c, review: ${report.codeReview.length}c, attack: ${report.attackReview.length}c`);
      }

      // Gap Analysis (skip on last round)
      if (round < this.maxGapRounds) {
        this.log.info(`── Phase 2.5: Gap Analysis (round ${round + 1}) ──`);
        const gapResult = await this.runGapAnalysis(
          player, allSubTasks, allTaskReports, entryFile, userIntent,
        );

        if (gapResult.gaps.length === 0) {
          this.log.info('  ✓ No gaps found, done');
          break;
        }

        this.log.info(`  ⟳ Found ${gapResult.gaps.length} gaps, spawning new tasks`);
        currentBatch = gapResult.gaps;
        allSubTasks = [...allSubTasks, ...gapResult.gaps];
      } else {
        this.log.info(`  Max gap rounds (${this.maxGapRounds}) reached`);
      }
    }

    // ── Assemble ──
    const report = this.buildReport(allTaskReports);
    this.log.info('✅ Audit pipeline finished');
    return report;
  }

  // ─── Per-SubTask Runner ──────────────────

  /**
   * 在一个对话里依次执行 implement → review → attack
   *
   * implement 开新对话 (第一条消息)
   * review 和 attack 作为 follow-up (同一对话)
   */
  private async runSubTask(
    player: Player,
    st: SubTask,
    entryFile: string,
    userIntent: string,
  ): Promise<TaskReport> {
    // ── Implement (开新对话) ──
    const implTask: Task = {
      id: `implement_${st.id}`,
      intention: st.intention,
      type: 'implement',
      status: 'pending',
      dependsOn: [],
      createdAt: Date.now(),
      context: {
        entryFile,
        userIntent,
        extra: {
          system_prompt: IMPLEMENTATION_SYSTEM_PROMPT,
          task_intention: st.intention,
        },
      },
    };

    this.events.onTaskStart?.(implTask);
    const implResult = await player.executeTask(implTask); // 开新对话
    this.events.onTaskDone?.(implTask, implResult);
    this.log.info(`  ${implResult.status === 'success' ? '✅' : '❌'} implement_${st.id}`);

    const report: TaskReport = {
      taskId: st.id,
      intention: st.intention,
      implementation: implResult.response,
      codeReview: '',
      attackReview: '',
    };

    // 如果 implement 失败，跳过 review + attack
    if (implResult.status !== 'success') return report;

    // ── Review (同一对话 follow-up) ──
    const reviewTask: Task = {
      id: `review_${st.id}`,
      intention: `Now perform a code quality review on the implementation you just analyzed.`,
      type: 'review',
      status: 'pending',
      dependsOn: [],
      createdAt: Date.now(),
      context: {
        extra: {
          system_prompt: REVIEWER_SYSTEM_PROMPT,
        },
      },
    };

    this.events.onTaskStart?.(reviewTask);
    const reviewResult = await player.executeTask(reviewTask, { continueConversation: true });
    this.events.onTaskDone?.(reviewTask, reviewResult);
    this.log.info(`  ${reviewResult.status === 'success' ? '✅' : '❌'} review_${st.id}`);
    report.codeReview = reviewResult.response;

    // ── Attack (同一对话 follow-up) ──
    const attackTask: Task = {
      id: `attack_${st.id}`,
      intention: `Now act as a Red Team attacker. Compare the original user intention with the implementation you analyzed and find deep business logic flaws.`,
      type: 'attack',
      status: 'pending',
      dependsOn: [],
      createdAt: Date.now(),
      context: {
        extra: {
          system_prompt: ATTACKER_SYSTEM_PROMPT,
        },
      },
    };

    this.events.onTaskStart?.(attackTask);
    const attackResult = await player.executeTask(attackTask, { continueConversation: true });
    this.events.onTaskDone?.(attackTask, attackResult);
    this.log.info(`  ${attackResult.status === 'success' ? '✅' : '❌'} attack_${st.id}`);
    report.attackReview = attackResult.response;

    return report;
  }

  // ─── Phase Runners ───────────────────────

  /** Phase 1: Intention — 探索项目 + 拆分子任务 (独立对话) */
  private async runIntention(
    player: Player,
    entryFile: string,
    userIntent: string,
  ): Promise<TaskResult> {
    const task: Task = {
      id: 'intention',
      intention: 'Explore the project and break down the review into sub-tasks',
      type: 'intention',
      status: 'pending',
      dependsOn: [],
      createdAt: Date.now(),
      context: {
        entryFile,
        userIntent,
        extra: { system_prompt: INTENTION_SYSTEM_PROMPT },
      },
    };

    this.events.onTaskStart?.(task);
    const result = await player.executeTask(task); // 开新对话
    this.events.onTaskDone?.(task, result);
    return result;
  }

  /** Phase 2.5: Gap Analysis (独立对话) */
  private async runGapAnalysis(
    player: Player,
    allSubTasks: SubTask[],
    allReports: TaskReport[],
    entryFile: string,
    userIntent: string,
  ): Promise<GapResult> {
    // 构造摘要
    const summaries = allReports
      .map(r => [
        `## Task: ${r.taskId}`,
        `**Intention:** ${r.intention}`,
        `**Implementation (first 1000 chars):**`,
        r.implementation.slice(0, 1000),
      ].join('\n'))
      .join('\n\n---\n\n');

    const gapPrompt = [
      `Entry File: ${entryFile}`,
      `User Intent: ${userIntent}`,
      '',
      '## Existing Implementation Reports',
      '',
      summaries,
    ].join('\n');

    const task: Task = {
      id: 'gap_analysis',
      intention: gapPrompt,
      type: 'gap_analysis',
      status: 'pending',
      dependsOn: [],
      createdAt: Date.now(),
      context: {
        entryFile,
        userIntent,
        extra: { system_prompt: GAP_ANALYZER_SYSTEM_PROMPT },
      },
    };

    this.events.onTaskStart?.(task);
    const result = await player.executeTask(task); // 开新对话
    this.events.onTaskDone?.(task, result);

    // 解析 JSON
    const parsed = extractJSON<{
      completeness_score?: number;
      gaps?: Array<{ id: string; intention: string }>;
      duplicates?: Array<{ keep: string; remove: string; reason: string }>;
    }>(result.response);

    return {
      completenessScore: parsed?.completeness_score ?? 0,
      gaps: (parsed?.gaps ?? [])
        .filter(g => g.id && g.intention)
        .map(g => ({ id: g.id, intention: g.intention })),
      duplicates: parsed?.duplicates ?? [],
    };
  }

  // ─── Parsers ─────────────────────────────

  /** 解析 Intention 输出的 JSON 子任务列表 */
  private parseIntentionTasks(response: string, fallbackIntent: string): SubTask[] {
    // 尝试 extractJSON
    const parsed = extractJSON<Array<{ id: string; intention: string }>>(response);
    if (Array.isArray(parsed) && parsed.length > 0) {
      return parsed
        .filter(p => p.id && p.intention)
        .map((p, i) => ({ id: p.id ?? `task_${i + 1}`, intention: p.intention }));
    }

    // Fallback: 正则提取 JSON 数组
    const match = response.match(/\[[\s\S]*\]/);
    if (match) {
      try {
        const arr = JSON.parse(match[0]) as Array<{ id?: string; intention?: string }>;
        if (Array.isArray(arr)) {
          return arr
            .filter(p => p.intention)
            .map((p, i) => ({ id: p.id ?? `task_${i + 1}`, intention: p.intention! }));
        }
      } catch { /* ignore */ }
    }

    // 最终 fallback
    return [{ id: 'fallback', intention: fallbackIntent }];
  }

  // ─── Report Builder ──────────────────────

  private buildReport(
    taskReports: TaskReport[],
    summary?: string,
  ): AuditReport {
    const autoSummary = summary ?? `${taskReports.length} sub-tasks analyzed.`;

    return {
      tasks: taskReports,
      summary: autoSummary,
      toMarkdown() {
        const lines: string[] = [];
        lines.push('# Code Review Report\n');

        lines.push('## Overview\n');
        lines.push(`- **Tasks analyzed**: ${taskReports.length}`);
        lines.push('');

        for (const task of taskReports) {
          lines.push(`---\n\n## [${task.taskId}] ${task.intention.slice(0, 80)}\n`);

          lines.push('### 🎯 Intention\n');
          lines.push(task.intention);
          lines.push('');

          lines.push('### 🔍 Discovered Implementation\n');
          lines.push(task.implementation || '_No implementation found._');
          lines.push('');

          lines.push('### 🛠️ Ground Review\n');
          lines.push(task.codeReview || '_No review generated._');
          lines.push('');

          lines.push('### ⚔️ Intention Attacker\n');
          lines.push(task.attackReview || '_No attack generated._');
          lines.push('');
        }

        return lines.join('\n');
      },
    };
  }
}
